[Service]
ExecStart=
ExecStart=/usr/bin/python3 -m synapse.app.homeserver --no-secrets-in-config --config-path=/etc/synapse/homeserver.yaml --config-path=/etc/synapse/email.yaml
ExecStop=
Restart=always
RestartMaxDelaySec=10s
RestartSec=100ms
RestartSteps=5
RuntimeDirectoryMode=0750
RuntimeDirectoryPreserve=yes
