#!/bin/bash

set -o errexit -o nounset -o pipefail

./process-static

remote=root@matrix.grapheneos.org
active=$(ssh $remote readlink /srv/element.grapheneos.org)

if [[ $active = /srv/element.grapheneos.org_a ]]; then
    target=/srv/element.grapheneos.org_b
else
    target=/srv/element.grapheneos.org_a
fi

echo active is $active
echo target is $target
echo

ssh $remote rm -rf $target
ssh $remote cp -a $active $target
rsync -rpcv --chmod=D755,F644 --delete static-tmp/ $remote:$target
ssh $remote sync -f $target
ssh $remote ln -snf $target /srv/element.grapheneos.org
ssh $remote sync /srv/element.grapheneos.org

sed -i "s|/srv/element.grapheneos.org|$target|" nginx-tmp/nginx.conf
rsync -rpcv --chmod=D755,F644 --delete nginx-tmp/nginx.conf $remote:/etc/nginx/nginx.conf
ssh $remote sync -f /etc/nginx/nginx.conf
ssh $remote nginx -s reload

echo
echo active is now $target
