#!/bin/bash

set -o errexit -o nounset -o pipefail

timestamp=$(date -u +%Y-%m-%dT%H:%M:%SZ)
rm -rf remote-backup
mkdir remote-backup

mkdir remote-backup/$timestamp
pg_dumpall -U postgres > remote-backup/$timestamp/all_databases.sql
cp -r /etc/matterbridge.toml remote-backup/$timestamp/matterbridge.toml
cp -r /etc/synapse remote-backup/$timestamp/synapse
cp -r /var/lib/mjolnir remote-backup/$timestamp/mjolnir
tar -cC remote-backup $timestamp | zstd -9 --long | age -r $(cat backup-public-key.txt) -o remote-backup/$timestamp.tar.zst.age

expiry=$(date -ud '+60 day' +%s)

source cloud-archive.sh

swift upload --skip-container-put --segment-size 5368709122 -H "X-Delete-At: $expiry" \
    --object-name $timestamp.tar.zst.age backup remote-backup/$timestamp.tar.zst.age

# work around https://bugs.launchpad.net/python-swiftclient/+bug/1478830
for segment in $(swift list backup_segments -p $timestamp.tar.zst.age/); do
    swift post -H "X-Delete-At: $expiry" backup_segments "$segment"
done

rm -rf remote-backup
